//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESS_project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Circulation { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Period { get; set; }
        public Nullable<int> Demand { get; set; }
        public Nullable<int> Publishing_FK { get; set; }
        public Nullable<int> Type_FK { get; set; }
        public Nullable<int> Country_FK { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Publishing Publishing { get; set; }
        public virtual Type Type { get; set; }
    }
}
